dist: xenial
sudo: false

language: node_js
node_js:
    - '10'

cache:
    directories:
        - ./node_modules

install:
    - yarn install

before_deploy:
    - yarn run build --prod --base-href /sr-traffic/
    - cp dist/sr-traffic/index.html dist/sr-traffic/404.html

deploy:
    provider: pages
    skip_cleanup: false
    github_token: $GITHUB_TOKEN
    local_dir: dist/sr-traffic
    on:
        branch: main
